NodeOUs:
  Enable: true
  ClientOUIdentifier:
    Certificate: cacerts/ca.auditor.auction.com-cert.pem
    OrganizationalUnitIdentifier: client
  PeerOUIdentifier:
    Certificate: cacerts/ca.auditor.auction.com-cert.pem
    OrganizationalUnitIdentifier: peer
